# Generated by Django 5.2.7 on 2025-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('LastName', models.CharField()),
                ('email', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='HistoryXY',
        ),
    ]
