# Generated by Django 5.2.7 on 2025-10-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accounts_delete_historyxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(verbose_name='Имя')),
                ('LastName', models.CharField(verbose_name='Фамилия')),
                ('email', models.CharField(verbose_name='Почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
