# Generated by Django 5.2.7 on 2025-11-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
