# Generated by Django 5.2.7 on 2025-10-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_delete_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Name',
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
    ]
