# Generated by Django 5.2.7 on 2025-11-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_lastname_remove_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='Пароль'),
        ),
    ]
