# Generated by Django 5.2.7 on 2025-11-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
