# Generated by Django 5.2.7 on 2025-11-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='session_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
